universe = container

## REPLACE WITH THE PATH TO SIF FILE ##
container_image = file:///staging/ptran5/apptainer/alphafold-2.3.2.sif

staging = /staging/ptran5

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# Change multimer.sh to monomer.sh if necessary

transfer_input_files = tests/$(FASTA_file),alphafold.sh,multimer.sh,monomer.sh,run_alphafold.py

# This should be the bash script
executable = alphafold.sh

# arguments passed to executable SH file as $1 $2 $3 $4
arguments = /gpulab_data/alphafold_2023_06_09 $(FASTA_file) $(staging) 2023-06-01

request_cpus = 4
request_memory = 20GB
request_disk = 100GB

requirements = (HasGpulabData == true) && (Target.HasCHTCStaging == true) && (OpSysMajorVer > 7)
request_GPUs = 1
+WantGPULab = true
require_gpus = (GlobalMemoryMb >= 60000)

error   = logs/alphafold_$(process)_$(cluster).err
output  = logs/alphafold_$(process)_$(cluster).out
log     = logs/alphafold_$(process)_$(cluster).log

queue FASTA_file from fastalist.txt